#!/bin/sh

set -e -x
export H=$(pwd)
export A=$($H/utils/platform)

. $H/config
. $H/utils/utils

. $H/utils/prepare-root

. $H/stage0/gcc3
. $H/stage0/musl
. $H/stage0/busybox
. $H/stage0/binutils
. $H/stage0/make
. $H/stage0/mk

. $H/stage0/finish
