#!/bin/sh

set -e -x
export H=$(pwd)

. $H/config
. $H/utils

. $H/pkg/gnu-grep
. $H/pkg/ncurses
. $H/pkg/patch
. $H/pkg/diffutils
. $H/pkg/less
. $H/pkg/flex
. $H/pkg/psmisc
. $H/pkg/bison
. $H/pkg/file
. $H/pkg/vim
. $H/pkg/lynx
. $H/pkg/autoconf
. $H/pkg/automake
