#!/bin/sh

set -e -x
export H=$(pwd)

. $H/config
. $H/utils

. $H/stage1-m4
. $H/stage1-sed
. $H/stage1-gawk

. $H/stage1-gmp
. $H/stage1-mpfr
. $H/stage1-mpc

. $H/stage1-gcc4

. $H/stage1-binutils
. $H/stage1-make

. $H/stage1-perl

. $H/stage1-kernel

. $H/stage1-busybox

. $H/stage1-extlinux

. $H/stage1-pkg-config
. $H/stage1-e2fsprogs

. $H/stage1-zlib
. $H/stage1-openssl
. $H/stage1-openssh

. $H/stage1-curl
. $H/stage1-git

. $H/stage1-9base
