#!/bin/sh
# release - package file sets

H=$(pwd)
RELEASE=sabotage-$(date -Idate)
mkdir -p $H/dist/$RELEASE
for s in base comp doc etc kernel xorg; do
  cd /
  sed 's/^/./' <$H/sets/$s |bsdcpio -o -H ustar |xz -e >$H/dist/$RELEASE/$s.tar.xz
  ls -l $H/dist/$RELEASE/$s*
done
cd $H/dist/$RELEASE
sha1sum *.*z* >SHA1SUMS
