#!/bin/sh
# release - package file sets

RELEASE=sabotage-$(date -Idate)
mkdir -p dist/$RELEASE
for s in base comp doc etc kernel; do
  cpio -o -H ustar <sets/$s |xz -e >dist/$RELEASE/$s.tar.xz
  ls -l dist/$RELEASE/$s.cpio.gz
done
cd dist/$RELEASE
sha1sum *.*z* >SHA1SUMS
